server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: XXX
    password: XXX
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

logging:
  level:
    root: info
    com.macro.mall: debug